//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSocialSatelliteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterAccess
    {
        public long ProfileID { get; set; }
        public string UserName { get; set; }
        public string AccessToken { get; set; }
        public string AccessTokenSecret { get; set; }
        public string ConsumerKey { get; set; }
    }
}
